title: Humbugs
description: Purveyor of Quality Confectionery
baseurl: /front
url: ''

# Jekyll-Store Engine
defaultAddress:
  country: GB
payment:
  tokenizer: Paymill
  currency: GBP
  hook: ''
tracking_id: ''

# Jekll-Store Front
image_prefix: ''
paymillPublicKey:
wake_up: ''
disqus_shortname: ''

# http://openexchangerates.github.io/accounting.js/#documentation
accounting:
  symbol : '£'
  format: '%s%v'
  decimal : '.'
  thousand: ','
  precision : 2

# https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  ignore:
    - _includes
    - _layouts
    - assets
    - json
    - node_modules
    - pages
    - .gitignore
    - _config.yml
    - CNAME
    - Gemfile
    - package.json
    - README.md
  metadata:
    _products:
      - name: name
        field:
          element: text
          label: Name
          help: Must be unique
      - name: price
        field:
          element: number
          label: 'Price (£)'
      - name: weight
        field:
          element: number
          label: 'Weight (kg)'
      - name: designer
        field:
          element: text
          label: Designer
      - name: type
        field:
          element: select
          label: Type
          options:
            - value: Wood
            - value: Metal
            - value: Metallic
      - name: condition
        field:
          element: select
          label: Condition
          options:
            - value: Mint
            - value: Worn
            - value: Rough
      - name: image
        field:
          element: text
          label: Image
      - name: big_image
        field:
          element: text
          label: Big Image

# http://jekyllrb.com/docs/configuration/
permalink: blog/:title
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  products:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: products
    values:
      layout: product
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - package.json